config/routes.rb
# coding: utf-8
PittalysoCloud::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  # （Web　=>　Resources）
  resources :items,             only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :categories,        only: [:index, :new, :create, :edit, :update, :destroy]
  resources :staffs,            only: [:index, :new, :create, :edit, :update, :destroy]
  resources :offices,           only: [:index, :new, :create, :edit, :update, :destroy]
  resources :licenses,          only: [:index, :new, :create, :edit, :update] do
    member do
      post 'stop'
      post 'start'
    end
  end
  resources :common_heads,      only: [:index, :new, :create, :edit, :update, :destroy], path: 'mylists'
  resources :results,           only: [:index], path: 'dashboard'

  match :upload, to: 'upload#import_file'
  match :download, to: 'download#search'
  get   'download/search'
  get   'download/export_file'
  get   'downloal/model'

  # （端末　=>　Resources）
  namespace :api do
    namespace :v1 do
      resources :tokens,            only: [:create]
      resources :items,             only: [:index]
      resources :staffs,            only: [:index]
      resources :offices,           only: [:index]
      resources :categories,        only: [:index]
      resources :common_heads,      only: [:index], path: 'mylists'
      resources :results,           only: [:create]
      resources :sync_histories,    only: [:index]
      get 'licenses/check'
      post "send_mail/device_csv"
    end
  end

  root to: 'results#index'

  # Static Pages
  match ':action', to: 'static#:action'

  # Routing Error処理
  match '*a', to: 'errors#routing'
end

app/models/staff.rb
# coding: utf-8
class Staff < ActiveRecord::Base
  # ===============
  # Mass Assignment
  # ===============
  attr_accessible :user_id, :cd, :name, :office_cd

  # ===========
  # Association
  # ===========
  belongs_to  :user
  has_many    :result_heads

  # =========
  # Validates
  # =========
  validates :cd,          presence: true,   uniqueness: { scope: :user_id }
  validates :name,        presence: true

  # =====
  # Scope
  # =====
  scope :user_staffs,   lambda { |user| where('user_id = ?', user.id) }
  scope :order_by_id,   lambda { order('id') }

  # ============
  # Class Method
  # ============
  def self.user_staff(user, id)
    where('user_id = ? and id = ?', user.id, id).first
  end

  def self.user_new(user)
    new({user_id: user.id})
  end

  def self.user_staff_create(user, params)
    new({
      user_id:    user.id,
      cd:         params[:cd],
      name:       params[:name],
      office_cd:  params[:office_cd]
    })
  end

  def self.user_staff_import_from_csv(user, row)
    new({
      user_id:    user.id,
      cd:         row[0],
      name:       row[1],
      office_cd:  row[2]
    })
  end
end

app/controllers/api/v1/staffs_controller.rb
# coding: utf-8
class Api::V1::StaffsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json

  # ユーザの担当者一覧を出力する
  def index
    @staffs = Staff.user_staffs(current_user).order_by_id
    respond_with @staffs
  end
end

app/controllers/staffs_controller.rb
# coding: utf-8
class StaffsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  # GET /staffs
  def index
    gon.url = staffs_url
    @staffs = Staff.user_staffs(current_user)
              .page(params[:page])
              .per(params[:per])
              .order(:cd)
    if params[:keyword]
      wc = "%"
      keyword = wc + params[:keyword] + wc
      @staffs = @staffs.where("name like ?", keyword)
    end
    respond_with @staffs
  end

  # GET /staffs/new
  def new
    @staff = Staff.user_new(current_user)
    respond_with @staff
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.user_staff(current_user, params[:id])
    # ユーザが保持するID以外を指定した場合は、一覧ページにリダイレクトさせる
    redirect_to staffs_url, alert: t('controllers.staffs.alert.find') and return if @staff.blank?

    respond_with @staff
  end

  # POST /staffs
  def create
    @staff = Staff.user_staff_create(current_user, params[:staff])

    if params[:staff][:cd].to_i <= 0
      @staff.errors[:base] << t('controllers.staffs.alert.cd_minus')
      render action: "new" and return
    end

    begin
      ActiveRecord::Base.transaction() do
        if @staff.save
          create_or_update_sync_history(SYNC_HISTORY_STAFF)
          redirect_to staffs_url, notice: t('controllers.staffs.notice.create')
        else
          render action: "new"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@staff)
    end
  end

  # PUT /staffs/1
  def update
    @staff = Staff.user_staff(current_user, params[:id])

    if params[:staff][:cd].to_i <= 0
      @staff.errors[:base] << t('controllers.staffs.alert.cd_minus')
      render action: "edit" and return
    end

    begin
      ActiveRecord::Base.transaction() do
        if @staff.update_attributes(params[:staff])
          create_or_update_sync_history(SYNC_HISTORY_STAFF)
          redirect_to staffs_url, notice: t('controllers.staffs.notice.update')
        else
          render action: "edit"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@staff)
    end
  end

  # DELETE /staffs/1
  def destroy
    @staff = Staff.user_staff(current_user, params[:id])

    begin
      ActiveRecord::Base.transaction() do
        @staff.destroy
        create_or_update_sync_history(SYNC_HISTORY_STAFF)
        redirect_to staffs_url, notice: t('controllers.staffs.notice.destroy')
      end
    rescue => e
      puts e.message
      redirect_to staffs_url, notice: t('exception.delete_error')
    end
  end
end

app/views/staffs/_form.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'staffs' %>
<% end %>

<%= form_for @staff, html: {class: "form-horizontal"} do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><strong><%= msg %></strong></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label"><%= f.label :cd %></label>
    <div class="controls">
      <%= f.text_field :cd, class: 'span1' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"><%= f.label :name %></label>
    <div class="controls">
      <%= f.text_field :name, class: 'span3' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"><%= f.label :office_cd %></label>
    <div class="controls">
      <div class="input-prepend" id="input_office_cd">
        <button class="btn search" type="button"><i class="icon-search"></i></button>
        <%= f.text_field :office_cd, class: "span1" %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit t('buttons.save'), class: "btn btn-warning btn-large" %>
    <%= link_to t('buttons.back'), staffs_path, class: "btn btn-large" %>
  </div>
<% end %>

<%= render partial: "download/modal" %>

app/views/staffs/edit.html.erb
<div class="page-header">
  <h3><%= t('views.staffs.actions.edit.title').html_safe %></h3>
</div>
<%= render 'form' %>

app/views/staffs/index.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'display_condition' %>
<% end %>

<div class="page-header">
  <h3><%= t('views.staffs.actions.index.title').html_safe %></h3>
</div>

<div class="well">
  <%= link_to t('buttons.new').html_safe, new_staff_path, class: "btn btn-primary" %>
</div>

<%= render partial: "shared/display_condition" %>

<%= paginate @staffs %>

<table class="table table-striped table-hover table-bordered" id="datatable">
  <thead>
    <tr>
      <th class="span2"><%= t('activerecord.attributes.staff.cd') %></th>
      <th><%= t('activerecord.attributes.staff.name') %></th>
      <th><%= t("activerecord.attributes.office.name") %></th>
      <th class="span2"></th>
      <th class="span2"></th>
    </tr>
  </thead>
  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.cd %></td>
        <td><%= staff.name %></td>
        <% if !staff.office_cd.blank? %>
          <% office = Office.find_by_cd(@current_user.id, staff.office_cd).first %>
          <% if !office.nil? %>
            <td><%= office.name %></td>
          <% else %>
            <td></td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>
        <td style="text-Align:center;"><%= link_to t('buttons.edit').html_safe, edit_staff_path(staff), class: "btn btn-warning" %></td>
        <td style="text-Align:center;"><%= destroy_link_to staff %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/staffs/new.html.erb
<div class="page-header">
  <h3><%= t('views.staffs.actions.new.title').html_safe %></h3>
</div>
<%= render 'form' %>