config/routes.rb
# coding: utf-8
PittalysoCloud::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  # （Web　=>　Resources）
  resources :items,             only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :categories,        only: [:index, :new, :create, :edit, :update, :destroy]
  resources :staffs,            only: [:index, :new, :create, :edit, :update, :destroy]
  resources :offices,           only: [:index, :new, :create, :edit, :update, :destroy]
  resources :licenses,          only: [:index, :new, :create, :edit, :update] do
    member do
      post 'stop'
      post 'start'
    end
  end
  resources :common_heads,      only: [:index, :new, :create, :edit, :update, :destroy], path: 'mylists'
  resources :results,           only: [:index], path: 'dashboard'

  match :upload, to: 'upload#import_file'
  match :download, to: 'download#search'
  get   'download/search'
  get   'download/export_file'
  get   'downloal/model'

  # （端末　=>　Resources）
  namespace :api do
    namespace :v1 do
      resources :tokens,            only: [:create]
      resources :items,             only: [:index]
      resources :staffs,            only: [:index]
      resources :offices,           only: [:index]
      resources :categories,        only: [:index]
      resources :common_heads,      only: [:index], path: 'mylists'
      resources :results,           only: [:create]
      resources :sync_histories,    only: [:index]
      get 'licenses/check'
      post "send_mail/device_csv"
    end
  end

  root to: 'results#index'

  # Static Pages
  match ':action', to: 'static#:action'

  # Routing Error処理
  match '*a', to: 'errors#routing'
end

app/models/office.rb
# coding: utf-8
class Office < ActiveRecord::Base
  # ===============
  # Mass Assignment
  # ===============
  attr_accessible :user_id, :cd, :name

  # ===========
  # Association
  # ===========
  belongs_to  :user
  has_many    :result_heads

  # =========
  # Validates
  # =========
  validates :cd,    presence: true,   uniqueness: { scope: :user_id }
  validates :name,  presence: true

  # =====
  # Scope
  # =====
  scope :user_offices,  lambda { |user| where('user_id = ?', user.id) }
  scope :order_by_id,   lambda { order('id') }
  scope :find_by_cd,    lambda { |user_id, cd| where("user_id = ? and cd = ?", user_id, cd) }

  # ============
  # Class Method
  # ============
  def self.user_office(user, id)
    where('user_id = ? and id = ?', user.id, id).first
  end

  def self.user_new(user)
    new({user_id: user.id})
  end

  def self.user_office_create(user, params)
    new({
      user_id:  user.id,
      cd:       params[:cd],
      name:     params[:name]
    })
  end

  def self.user_office_import_from_csv(user, row)
    new({
      user_id:  user.id,
      cd:       row[0],
      name:     row[1]
    })
  end
end

app/controllers/api/v1/offices_controller.rb
# coding: utf-8
class Api::V1::OfficesController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json

  # ユーザの店舗一覧を出力する
  def index
    @offices = Office.user_offices(current_user).order_by_id
    respond_with @offices
  end
end

app/controllers/offices_controller.rb
# coding: utf-8
class OfficesController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  # GET /offices
  def index
    gon.url = offices_url
    @offices =  Office.user_offices(current_user)
                .page(params[:page])
                .per(params[:per])
                .order(:cd)
    if params[:keyword]
      wc = "%"
      keyword = wc + params[:keyword] + wc
      @offices = @offices.where("name like ?", keyword)
    end
    respond_with @offices
  end

  # GET /offices/new
  def new
    @office = Office.user_new(current_user)
    respond_with @office
  end

  # GET /offices/1/edit
  def edit
    @office = Office.user_office(current_user, params[:id])
    # ユーザが保持するID以外を指定した場合は、一覧ページにリダイレクトさせる
    redirect_to offices_url, alert: t('controllers.offices.alert.find') and return if @office.blank?

    respond_with @office
  end

  # POST /offices
  def create
    @office = Office.user_office_create(current_user, params[:office])

    if params[:office][:cd].to_i <= 0
      @office.errors[:base] << t('controllers.offices.alert.cd_minus')
      render action: "new" and return
    end

    begin
      ActiveRecord::Base.transaction() do
        if @office.save
          create_or_update_sync_history(SYNC_HISTORY_OFFICE)
          redirect_to offices_url, notice: t('controllers.offices.notice.create')
        else
          render action: "new"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@office)
    end
  end

  # PUT /offices/1
  def update
    @office = Office.user_office(current_user, params[:id])

    if params[:office][:cd].to_i <= 0
      @office.errors[:base] << t('controllers.offices.alert.cd_minus')
      render action: "edit" and return
    end

    begin
      ActiveRecord::Base.transaction() do
        if @office.update_attributes(params[:office])
          create_or_update_sync_history(SYNC_HISTORY_OFFICE)
          redirect_to offices_url, notice: t('controllers.offices.notice.update')
        else
          render action: "edit"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@office)
    end
  end

  # DELETE /offices/1
  def destroy
    @office = Office.user_office(current_user, params[:id])

    begin
      ActiveRecord::Base.transaction() do
        @office.destroy
        create_or_update_sync_history(SYNC_HISTORY_OFFICE)
        redirect_to offices_url, notice: t('controllers.offices.notice.destroy')
      end
    rescue => e
      puts e.message
      redirect_to offices_url, notice: t('exception.delete_error')
    end
  end
end

app/views/offices/_form.html.erb
<%= form_for @office, html: {class: "form-horizontal"} do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><strong><%= msg %></strong></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label"><%= f.label :cd %></label>
    <div class="controls">
      <%= f.text_field :cd, class: 'span1' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"><%= f.label :name %></label>
    <div class="controls">
      <%= f.text_field :name, class: 'span3' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit t('buttons.save'), class: "btn btn-warning btn-large" %>
    <%= link_to t('buttons.back'), offices_path, class: "btn btn-large" %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<div class="page-header">
  <h3><%= t('views.offices.actions.edit.title').html_safe %></h3>
</div>
<%= render 'form' %>

app/views/offices/index.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'display_condition' %>
<% end %>

<div class="page-header">
  <h3><%= t('views.offices.actions.index.title').html_safe %></h3>
</div>

<div class="well">
  <%= link_to t('buttons.new').html_safe, new_office_path, class: "btn btn-primary" %>
</div>

<%= render partial: "shared/display_condition" %>

<%= paginate @offices %>

<table class="table table-striped table-hover table-bordered" id="datatable">
  <thead>
    <tr>
      <th class="span2"><%= t('activerecord.attributes.office.cd') %></th>
      <th><%= t('activerecord.attributes.office.name') %></th>
      <th class="span2"></th>
      <th class="span2"></th>
    </tr>
  </thead>
  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.cd %></td>
        <td><%= office.name %></td>
        <td style="text-Align:center;"><%= link_to t('buttons.edit').html_safe, edit_office_path(office), class: "btn btn-warning" %></td>
        <td style="text-Align:center;"><%= destroy_link_to office %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offices/new.html.erb
<div class="page-header">
  <h3><%= t('views.offices.actions.new.title').html_safe %></h3>
</div>
<%= render 'form' %>