config/routes.rb
# coding: utf-8
PittalysoCloud::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  # （Web　=>　Resources）
  resources :items,             only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :categories,        only: [:index, :new, :create, :edit, :update, :destroy]
  resources :staffs,            only: [:index, :new, :create, :edit, :update, :destroy]
  resources :offices,           only: [:index, :new, :create, :edit, :update, :destroy]
  resources :licenses,          only: [:index, :new, :create, :edit, :update] do
    member do
      post 'stop'
      post 'start'
    end
  end
  resources :common_heads,      only: [:index, :new, :create, :edit, :update, :destroy], path: 'mylists'
  resources :results,           only: [:index], path: 'dashboard'

  match :upload, to: 'upload#import_file'
  match :download, to: 'download#search'
  get   'download/search'
  get   'download/export_file'
  get   'downloal/model'

  # （端末　=>　Resources）
  namespace :api do
    namespace :v1 do
      resources :tokens,            only: [:create]
      resources :items,             only: [:index]
      resources :staffs,            only: [:index]
      resources :offices,           only: [:index]
      resources :categories,        only: [:index]
      resources :common_heads,      only: [:index], path: 'mylists'
      resources :results,           only: [:create]
      resources :sync_histories,    only: [:index]
      get 'licenses/check'
      post "send_mail/device_csv"
    end
  end

  root to: 'results#index'

  # Static Pages
  match ':action', to: 'static#:action'

  # Routing Error処理
  match '*a', to: 'errors#routing'
end

app/models/common_head.rb
# coding: utf-8
class CommonHead < ActiveRecord::Base
  # ===============
  # Mass Assignment
  # ===============
  attr_accessible :user_id, :cd, :name, :common_bodies_attributes

  # ===========
  # Association
  # ===========
  belongs_to :user
  has_many   :common_bodies,  dependent: :delete_all
  accepts_nested_attributes_for :common_bodies, allow_destroy: true

  # =========
  # Validates
  # =========
  validates :cd,    presence: true,   uniqueness: { scope: :user_id }
  validates :name,  presence: true
  validates_associated :common_bodies

  # =====
  # Scope
  # =====
  scope :user_common_heads,     lambda { |user| where('user_id = ?', user.id) }
  scope :order_by_id,           lambda { order('id') }

  # ============
  # Class Method
  # ============
  def self.user_common_head(user, id)
    where('user_id = ? and id = ?', user.id, id).first
  end

  def self.user_new(user)
    new({user_id: user.id})
  end

  def self.user_common_head_create(user, params)
    new({
      user_id:                  user.id,
      cd:                       params[:cd],
      name:                     params[:name],
      common_bodies_attributes: params[:common_bodies_attributes]
    })
  end

  def self.user_common_head_import_from_csv(user, row)
    new({
      user_id:                  user.id,
      cd:                       row[0],
      name:                     row[1]
    })
  end
end

app/controllers/api/v1/common_heads_controller.rb
# coding: utf-8
class Api::V1::CommonHeadsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json

  def index
    @common_heads = CommonHead.user_common_heads(current_user).order_by_id
    respond_with @common_heads
  end
end

app/controllers/common_heads_controller.rb
# coding: utf-8
class CommonHeadsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html

  # GET /common_heads => /mylists
  def index
    gon.url = common_heads_url
    @common_heads = CommonHead.user_common_heads(current_user)
                    .page(params[:page])
                    .per(params[:per])
                    .order(:cd)
    if params[:keyword]
      wc = "%"
      keyword = wc + params[:keyword] + wc
      @common_heads = @common_heads.where("name like ?", keyword)
    end
    respond_with @common_heads
  end

  # GET /common_heads/1 => /mylists/1
  def show
    @common_head = CommonHead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @common_head }
    end
  end

  # GET /common_heads/new => /mylist/new
  def new
    @common_head = CommonHead.user_new(current_user)
    respond_with @common_head
  end

  # GET /common_heads/1/edit => /mylist/1/edit
  def edit
    @common_head = CommonHead.user_common_head(current_user, params[:id])
    # ユーザが保持するID以外を指定した場合は、一覧ページにリダイレクトさせる
    redirect_to common_heads_url, alert: t('controllers.common_heads.alert.find') and return if @common_head.blank?

    respond_with @common_head
  end

  # POST /common_heads => /mylists
  def create
    if params[:common_head][:cd].to_i <= 0
      @common_head = CommonHead.user_new(current_user)
      @common_head.cd = params[:common_head][:cd]
      @common_head.name = params[:common_head][:name]
      if !params[:common_head][:common_bodies_attributes].nil?
        @common_head.common_bodies_attributes = params[:common_head][:common_bodies_attributes]
      end
      @common_head.errors[:base] << t('controllers.common_heads.alert.cd_minus')
      render action: "new" and return
    end

    if params[:common_head][:common_bodies_attributes].nil?
      @common_head = CommonHead.user_new(current_user)
      @common_head.cd = params[:common_head][:cd]
      @common_head.name = params[:common_head][:name]
      @common_head.errors[:base] << t('controllers.common_heads.alert.blank')
      render action: "new" and return
    end

    @common_head = CommonHead.user_common_head_create(current_user, params[:common_head])

    begin
      ActiveRecord::Base.transaction() do
        if @common_head.save
          create_or_update_sync_history(SYNC_HISTORY_MYLIST)
          redirect_to common_heads_url, notice: t('controllers.common_heads.notice.create')
        else
          render action: "new"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@common_head)
    end
  end

  # PUT /common_heads/1 => /mylists/1
  def update
    @common_head = CommonHead.user_common_head(current_user, params[:id])

    if params[:common_head][:cd].to_i <= 0
      @common_head.errors[:base] << t('controllers.common_heads.alert.cd_minus')
      render action: "edit" and return
    end

    begin
      ActiveRecord::Base.transaction() do
        if @common_head.update_attributes(params[:common_head])
          if @common_head.common_bodies.count == 0
            destroy and return
          end
          create_or_update_sync_history(SYNC_HISTORY_MYLIST)
          redirect_to common_heads_url, notice: t('controllers.common_heads.notice.update')
        else
          render action: "edit"
        end
      end
    rescue => e
      puts e.message
      raise_save_error(@common_head)
    end
  end

  # DELETE /common_heads/1 => /mylists/1
  def destroy
    @common_head = CommonHead.user_common_head(current_user, params[:id])

    begin
      ActiveRecord::Base.transaction() do
        @common_head.destroy
        create_or_update_sync_history(SYNC_HISTORY_MYLIST)
        redirect_to common_heads_url, notice: t('controllers.common_heads.notice.destroy')
      end
    rescue => e
      puts e.message
      redirect_to common_heads_url, notice: t('exception.delete_error')
    end
  end
end

app/views/common_heads/_common_body_fields.html.erb
<% common_body = f.object %>
<tr class="fields">
  <% if common_body && common_body.skucd? %>
    <td><%= f.text_field :skucd, class: "item_skucd span2", readonly: true %></td>
    <% if common_body.common_head_id.nil? %>
      <% item = Item.user_item_by_skucd(current_user, common_body.skucd) %>
      <td><%= f.label item.jancd, class: "item_jancd" %></td>
      <td><%= f.label item.name, class: "item_name" %></td>
      <td><%= f.label item.kind, class: "item_kind" %></td>
      <td style="text-Align:right;"><%= f.label item.price, class: "item_price" %></td>
      <td style="text-Align:right;"><%= f.label item.carton, class: "item_carton" %></td>
    <% else %>
      <td><%= f.label common_body.item.jancd, class: "item_jancd" %></td>
      <td><%= f.label common_body.item.name, class: "item_name" %></td>
      <td><%= f.label common_body.item.kind, class: "item_kind" %></td>
      <td style="text-Align:right;"><%= f.label common_body.item.price, class: "item_price" %></td>
      <td style="text-Align:right;"><%= f.label common_body.item.carton, class: "item_carton" %></td>
    <% end %>
  <% else %>
    <td><%= f.text_field :skucd, class: "item_skucd span2", readonly: true %></td>
    <td><%= f.label :item_jancd, class: "item_jancd" %></td>
    <td><%= f.label :item_name, class: "item_name" %></td>
    <td><%= f.label :item_kind, class: "item_kind" %></td>
    <td style="text-Align:right;"><%= f.label :item_price, class: "item_price" %></td>
    <td style="text-Align:right;"><%= f.label :item_carton, class: "item_carton" %></td>
  <% end %>
  <td style="text-Align:center;"><%= f.link_to_remove t('buttons.destroy').html_safe, class: "btn btn-danger" %></td>
</tr>

app/views/common_heads/_form.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "common_heads" %>
<% end %>

<%= nested_form_for @common_head, html: {class: "form-horizontal"} do |f| %>
  <% if @common_head.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <ul>
      <% @common_head.errors.full_messages.each do |msg| %>
        <li><strong><%= msg %></strong></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label"><%= f.label :cd %></label>
    <div class="controls">
      <%= f.number_field :cd, class: 'span1' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"><%= f.label :name %></label>
    <div class="controls">
      <%= f.text_field :name, class: 'span3' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"><%= t('views.common_heads.actions.edit.add_item') %></label>
    <div class="controls">
      <p>
        <input class="span2 error" id="item_cd" type="text" />
        <button class="btn btn-info" id="item_search" type="button"><i class="icon-search"></i><%= t("views.common_heads.actions.form.search") %></button>
        <div class="checkbox">
          <input id="is_jan" type="checkbox" checked="false"><%= t("views.common_heads.actions.form.is_jan") %></input>
        </div>
      </p>
      <p>
        <input class="span2 uneditable-input" id="item_skucd" type="text" disabled="disabled" />
        <input class="span2 uneditable-input" id="item_jancd" type="text" disabled="disabled" />
        <input class="span3 uneditable-input" id="item_name" type="text" disabled="disabled" />
        <input class="span2 uneditable-input" id="item_kind" type="text" disabled="disabled" />
        <input class="span1 uneditable-input" id="item_price" type="text" disabled="disabled" style="text-Align:right;" />
        <input class="span1 uneditable-input" id="item_carton" type="text" disabled="disabled" style="text-Align:right;" />
      </p>
      <p>
        <%= f.link_to_add t('views.common_heads.actions.edit.btn_add_item').html_safe, :common_bodies, :data => { :target => "#common_bodies" }, class: "btn btn-primary", id: 'add_item'%>
      </p>
      <table class="table table-bordered table-striped" id="common_bodies">
        <thead>
          <tr>
            <th class="span2"><%= t('activerecord.attributes.item.skucd') %></th>
            <th><%= t('activerecord.attributes.item.jancd') %></th>
            <th><%= t('activerecord.attributes.item.name') %></th>
            <th><%= t('activerecord.attributes.item.kind') %></th>
            <th><%= t('activerecord.attributes.item.price') %></th>
            <th><%= t('activerecord.attributes.item.carton') %></th>
            <th class="span2"></th>
          </tr>
        </thead>
        <tbody>
          <%= f.fields_for :common_bodies, :wrapper => false %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit t('buttons.save'), class: "btn btn-warning btn-large" %>
    <%= link_to t('buttons.back'), common_heads_path, class: "btn btn-large" %>
  </div>
<% end %>

app/views/common_heads/edit.html.erb
<div class="page-header">
  <h3><%= t('views.common_heads.actions.edit.title').html_safe %></h3>
</div>

<%= render 'form' %>

app/views/common_heads/index.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'display_condition' %>
<% end %>

<div class="page-header">
  <h3><%= t('views.common_heads.actions.index.title').html_safe %></h3>
</div>

<div class="well">
  <%= link_to t('buttons.new').html_safe, new_common_head_path, class: "btn btn-primary" %>
</div>

<%= render partial: "shared/display_condition" %>

<%= paginate @common_heads %>

<table class="table table-striped table-hover table-bordered" id="datatable">
  <thead>
    <tr>
      <th class="span2"><%= t('activerecord.attributes.common_head.cd') %></th>
      <th ><%= t('activerecord.attributes.common_head.name') %></th>
      <th class="span2"><%= t('views.common_heads.actions.index.common_bodies_count') %></th>
      <th class="span2"></th>
      <th class="span2"></th>
    </tr>
  </thead>
  <tbody>
    <% @common_heads.each do |common_head| %>
      <tr>
        <td><%= common_head.cd %></td>
        <td><%= common_head.name %></td>
        <td style="text-Align:right;"><%= common_head.common_bodies.length %></td>
        <td style="text-Align:center;"><%= link_to t('buttons.edit').html_safe, edit_common_head_path(common_head), class: "btn btn-warning" %></td>
        <td style="text-Align:center;"><%= destroy_link_to common_head %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/common_heads/new.html.erb
<div class="page-header">
  <h3><%= t('views.common_heads.actions.new.title').html_safe %></h3>
</div>

<%= render 'form' %>