config/routes.rb
# coding: utf-8
PittalysoCloud::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  # （Web　=>　Resources）
  resources :items,             only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :categories,        only: [:index, :new, :create, :edit, :update, :destroy]
  resources :staffs,            only: [:index, :new, :create, :edit, :update, :destroy]
  resources :offices,           only: [:index, :new, :create, :edit, :update, :destroy]
  resources :licenses,          only: [:index, :new, :create, :edit, :update] do
    member do
      post 'stop'
      post 'start'
    end
  end
  resources :common_heads,      only: [:index, :new, :create, :edit, :update, :destroy], path: 'mylists'
  resources :results,           only: [:index], path: 'dashboard'

  match :upload, to: 'upload#import_file'
  match :download, to: 'download#search'
  get   'download/search'
  get   'download/export_file'
  get   'downloal/model'

  # （端末　=>　Resources）
  namespace :api do
    namespace :v1 do
      resources :tokens,            only: [:create]
      resources :items,             only: [:index]
      resources :staffs,            only: [:index]
      resources :offices,           only: [:index]
      resources :categories,        only: [:index]
      resources :common_heads,      only: [:index], path: 'mylists'
      resources :results,           only: [:create]
      resources :sync_histories,    only: [:index]
      get 'licenses/check'
      post "send_mail/device_csv"
    end
  end

  root to: 'results#index'

  # Static Pages
  match ':action', to: 'static#:action'

  # Routing Error処理
  match '*a', to: 'errors#routing'
end

app/views/shared/_display_condition.html.erb
<div>
  <% pers = [10, 25, 50, 100] %>
  <select class="page">
    <% pers.each do |per| %>
      <% if params[:per] === per.to_s %>
        <option value="<%= per %>" selected><%= per %></option>
      <% else %>
        <option value="<%= per %>"><%= per %></option>
      <% end %>
    <% end %>
  </select>
  <span><%= t("display_condition.number") %></span>
</div>

<div>
  <span></span>
  <div class="input-append" id="">
    <input type="text" id="keyword" class="span3" value="<%= params[:keyword] %>">
    <button class="btn search" id="search" type="button">
      <i class="icon-search"></i>
      <%= t("display_condition.search") %>
    </button>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="muted credit">Copyright&copy; 2013 <a href="http://www.usknet.com/" target="_blank">USAC SYSTEM CO.,LTD.</a> All Rights Reserved.</div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="<%= root_path %>"><%= t('title.pittaly') %></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to t('navbar.dashboard').html_safe, root_path %></li>
          <li><%= link_to t('navbar.license').html_safe, licenses_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('navbar.cloud').html_safe %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('navbar.upload').html_safe, upload_path %></li>
              <li><%= link_to t('navbar.download').html_safe, download_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('navbar.master').html_safe %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('navbar.item').html_safe, items_path %></li>
              <li><%= link_to t('navbar.office').html_safe, offices_path %></li>
              <li><%= link_to t('navbar.staff').html_safe, staffs_path %></li>
              <li><%= link_to t('navbar.category').html_safe, categories_path %></li>
              <li><%= link_to t('navbar.mylist').html_safe, common_heads_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('navbar.help').html_safe %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('navbar.specification').html_safe, "/specification" %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav pull-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user"></i> <%= current_user.profile.company %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t('navbar.logout').html_safe , destroy_user_session_path, method: 'delete' %>
              </li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_production_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-958580-12', 'pittaly.net');
  ga('send', 'pageview');

</script>

app/views/shared/_staging_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-958580-11', 'pittaly.net');
  ga('send', 'pageview');

</script>

app/views/shared/_static_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="<%= new_user_session_path %>"><%= t('title.pittaly') %></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to '<i class="icon-file-alt"></i> '.html_safe + "ファイルレイアウト" %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>